config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  get 'signup', to: 'people#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  post 'sms', to: 'sms#create', as: 'sms'

  resources :users
  resources :sessions

  resources :milestones
  resources :workouts
  resources :reminders do
    collection do
      put 'finish'
    end
  end
  resources :journals
  resources :contacts
  resources :connections
  resources :payments
  resources :accounts
  resources :people
  resources :links do
    collection do
      get 'find'
      get 'clean'
      get 'refresh_tags'
    end
  end
end

app/models/workout.rb
class Workout
  include Mongoid::Document
  include Mongoid::Timestamps::Short

  field :loc, as: :location
  field :rc, as: :race
  field :dsc, as: :description
  field :tg, as: :tags
  field :dur, as: :duration, type: Integer
  field :int, as: :intensity, type: Float
  field :wt, as: :weight, type: Integer
  field :di, as: :distance, type: Float
  field :w_on, as: :workout_on, type: Date
  field :st, as: :strava_id

  belongs_to :person
  belongs_to :route, class_name: 'Lookup', optional: true

  validates :location, presence: true
  validates :duration, presence: true
  validates :workout_on, presence: true
  paginates_per 10
  INTENSITIES = [
    ['1 - brisk walk', 1.0], ['1.5', 1.5], ['2', 2.0], ['2.5', 2.5], ['3 - very light jog', 3.0],
    ['3.5', 3.5], ['4', 4.0], ['4.5', 4.5], ['5 - standard workout', 5.0], ['5.5', 5.5], ['6', 6.0],
    ['6.5', 6.5], ['7 - something hard', 7.0], ['7.5', 7.5], ['8 - what am i doing this for?', 8.0],
    ['8.5', 8.5], ['9 - blacking out', 9.0], ['9.5', 9.5], ['10 - heart\'s about to explode', 10.0]
  ].freeze

  def self.recent_workouts(user, days)
    user.workouts.where(:workout_on.gte => Time.zone.today - days)
  end

  def self.days_with_workouts?(user, days)
    user.workouts.and({ :workout_on.gte => Time.zone.today - days }, :workout_on.lt => Time.zone.today + 1)
        .distinct(:workout_on).count
  end

  def self.workout_duration_by_tag(user, days)
    report = {}
    total_duration = 0
    workouts = recent_workouts(user, days)
    workouts.each do |w|
      next unless w.tags
      total_duration += w.duration
      # TODO: individual tag not all tags
      tags_list = w.tags.split(' ')
      tags_list.each do |tag|
        if report.key?(tag)
          report[tag][:duration] += w.duration
        else
          report[tag] = { duration: w.duration }
        end
      end
    end
    report.each_value do |tag|
      tag[:percentage] = ((tag[:duration] / total_duration.to_f) * 100).to_i || 1
    end
    report.sort { |a, b| b[1][:duration] <=> a[1][:duration] }
  end

  def self.summary(user, days)
    workouts = Workout.recent_workouts(user, days)
    mileage = 0
    duration = 0
    max_weight = 0
    min_weight = 999
    workouts.each do |w|
      mileage += w.distance if w.distance
      duration += w.duration if w.duration
      max_weight = w.weight if w.weight && w.weight > max_weight
      min_weight = w.weight if w.weight && w.weight < min_weight
    end
    {
      weight_range: "#{min_weight}-#{max_weight}",
      workout_days: Workout.days_with_workouts?(user, days),
      mileage: (mileage * 10).ceil / 10.0, # tenths of kms
      duration: (duration / 60 * 10).ceil / 10.0 # minutes to tenths of hours
    }
  end

  def to_s
    "#{tags} #{distance} - #{location}"
  end
end

app/controllers/workouts_controller.rb
require 'brainpad/strava_lib'

class WorkoutsController < ApplicationController
  before_action :set_workout, only: %i[show edit update destroy]

  # GET /workouts
  def index
    authorize Workout
    # fill in recent workouts from strava activities
    # TODO how far back do we look in the strava stream? 20 for now
    created_from_strava = Brainpad::StravaLib.import_for(current_user, 20)
    flash[:notice] = "created #{created_from_strava} new workouts from strava" if created_from_strava > 0

    @workouts = current_user.workouts.desc(:workout_on)
    if params[:tag]
      @workouts = @workouts.where(tags: /#{params[:tag]}/)
      @tag = params[:tag]
    end
    @workouts = @workouts.where(location: /#{params[:q]}/i) if params[:q]
    @workouts = @workouts.page(params[:page])
    @workout_summary = Workout.summary(current_user, 31)
    @workout_duration_by_tag = Workout.workout_duration_by_tag(current_user, 31)
  end

  # GET /workouts/1.js
  def show
    authorize @workout
  end

  # GET /workouts/new.js
  def new
    @routes = Lookup.where(category: 25).all
    @workout = params[:workout_id] ? @workout = Workout.find(params[:workout_id]).dup : Workout.new
  end

  # GET /workouts/1/edit.js
  def edit
    authorize @workout
    @routes = Lookup.where(category: 25).all
  end

  # POST /workouts
  def create
    @workout = current_user.workouts.build(workout_params)
    authorize @workout
    if @workout.save
      current_user.tag('workout', @workout.tags)
      flash[:notice] = 'workout was created.'
      redirect_to workouts_path
    end
  end

  # PUT /workouts/1
  def update
    authorize @workout
    if @workout.update_attributes!(workout_params)
      current_user.tag('workout', @workout.tags)
      flash[:notice] = 'workout was updated.'
      redirect_to workouts_path
    end
  end

  # DELETE /workouts/1
  def destroy
    authorize @workout
    @workout.destroy
    redirect_to workouts_path
  end

  private

  def set_workout
    @workout = Workout.find(params[:id])
  end

  def workout_params
    params.require(:workout).permit(
      :location, :race, :description, :tags, :duration, :intensity, :weight, :distance, :workout_on, :route_id,
      :strava_id
    )
  end
end

app/views/workouts/_duration_by_tag.html.erb
<div id="payments-top-tags" class="card">
    <div class="card-header"><h5>workout duration</h5></div>
    <div class="card-body">
        <% @workout_duration_by_tag.each do |w| %>
            <%= "#{w[0]} #{(Time.mktime(0)+(w[1][:duration]*60)).strftime("%H:%M")} [#{w[1][:percentage]}%]" %><br/>
            <%= image_tag('redbar.gif', width: "#{(w[1][:percentage]*1.5).to_i}", class: 'bar') %><br/>
        <% end %>
    </div>
</div>

app/views/workouts/_duration_by_type.html.erb
<div class="box">
	<div class="boxhead">workout duration</div>
	<div class="boxcontent">
		<% @workout_duration_by_type.each do |w| %>
			<%= "#{w[0]} #{(Time.mktime(0)+(w[1]['duration']*60)).strftime("%H:%M")} [#{w[1]['percentage']}%]" %><br/>
			<%= image_tag('redbar.gif', :width => "#{(w[1]['percentage']*1.5).to_i}", :class => 'bar') %><br/>
		<% end %>
	</div>
</div> <!-- end box -->

app/views/workouts/_form.html.erb
<%= form_with(model: @workout, local: true) do |f| %>
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><%= @workout.new_record? ? 'new' : 'update' %> workout</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container">
                    <div class="form-group row">
                        <%= f.label(:tags, class: 'col-sm-2 col-form-label text-right') %>
                        <div class="col-sm-6 pr-0">
                            <%= f.text_field(:tags, id: 'workout-tags', class: 'form-control focus') %>
                        </div>
                        <div class="col-sm-4 pl-0">
                            <%= render partial: 'shared/tags_field', locals: { kind: 'workout', desc_field: nil } %>
                        </div>
                    </div>
                    <div class="form-group row">
                        <%= f.label(:workout_on, 'On', class: 'col-sm-2 col-form-label text-right') %>
                        <div class="col-sm-4">
                            <%= f.text_field(:workout_on, id: 'workout-on', class: 'form-control') %>
                        </div>
                        <%= f.label(:location, class: 'col-sm-2 col-form-label text-right') %>
                        <div class="col-sm-4">
                          <%= f.text_field(:location, class: 'form-control') %>
                        </div>
                    </div>
                    <div class="form-group row">
                        <%= f.label(:race, class: 'col-sm-2 col-form-label text-right') %>
                        <div class="col-sm-4">
                            <%= f.text_field(:race, class: 'form-control') %>
                        </div>
                        <%= f.label(:route, class: 'col-sm-2 col-form-label text-right') %>
                        <div class="col-sm-4">
                          <%= f.collection_select(:route_id, @routes, :id, :description, { include_blank: true }, class: 'form-control') %>
                        </div>
                    </div>
                    <div class="form-group row">
                        <%= f.label(:distance, class: 'col-sm-2 col-form-label text-right') %>
                        <div class="col-sm-4">
                            <%= f.text_field(:distance, class: 'form-control') %>
                        </div>
                        <%= f.label(:duration, class: 'col-sm-2 col-form-label text-right') %>
                        <div class="col-sm-4">
                          <%= f.text_field(:duration, class: 'form-control') %>
                        </div>
                    </div>
                    <div class="form-group row">
                        <%= f.label(:intensity, class: 'col-sm-2 col-form-label text-right') %>
                        <div class="col-sm-4">
                            <%= f.select(:intensity, Workout::INTENSITIES, { include_blank: true }, class: 'form-control') %>
                        </div>
                        <%= f.label(:weight, class: 'col-sm-2 col-form-label text-right') %>
                        <div class="col-sm-4">
                          <%= f.text_field(:weight, class: 'form-control') %>
                        </div>
                    </div>
                    <div class="form-group row">
                        <%= f.label(:description, class: 'col-sm-2 col-form-label text-right') %>
                        <div class="col-sm-10">
                            <%= f.text_area(:description, rows: 3, class: 'form-control') %>
                        </div>
                    </div>
                </div>
            </div> <!-- end .modal-body -->
            <div class="modal-footer">
                <div class="form-group row text-right">
                    <div class="col">
                        <%= link_to('cancel', '#', data: { dismiss: 'modal' }) %>
                        <%= f.submit class: 'btn btn-primary' %>
                    </div>
                </div>
            </div> <!-- end .modal-footer -->
        </div> <!-- end .modal-content -->
    </div> <!-- end .modal-dialog -->
<% end %>

app/views/workouts/_show.html.erb
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">workout details</h5>
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-md-5 display-label">date</div>
                <div class="col-md-7"><%= @workout.workout_on.strftime("%a %b %d, %y") %></div>
            </div>
            <div class="row">
                <div class="col-md-5 display-label">tags</div>
                <div class="col-md-7"><%= @workout.tags %></div>
            </div>
            <div class="row">
                <div class="col-md-5 display-label">location</div>
                <div class="col-md-7"><%= @workout.location %></div>
            </div>
            <div class="row">
                <div class="col-md-5 display-label">description</div>
                <div class="col-md-7"><%= @workout.description %></div>
            </div>
            <div class="row">
                <div class="col-md-5 display-label">duration</div>
                <div class="col-md-7"><%= @workout.duration %></div>
            </div>
            <div class="row">
                <div class="col-md-5 display-label">distance</div>
                <div class="col-md-7"><%= @workout.distance %></div>
            </div>
        </div> <!-- /.modal-body -->
    </div> <!-- /.modal-content -->
</div> <!-- /.modal-dialog -->

app/views/workouts/_workouts.html.erb
<%= filters_links %>
<table class="table table-sm table-hover">
    <thead>
        <tr><th>date</th><th>type</th><th>location</th><th>km</th><th>min</th><th>actions</th></tr>
    </thead>
    <tbody>
    <% @workouts.each do |workout| %>
    <tr>
        <td><%= link_to(workout.workout_on.strftime("%a %b %d, %y"), edit_workout_path(workout), remote: true) %></td>
        <td><%= workout.tags %></td>
        <td>
            <% if workout.route %>
                <a href="http://www.gmap-pedometer.com/?r=<%= workout.route.code %>" target="_blank">
                    <%= workout.location %>
                </a>
            <% else %>
                <%= workout.location %>
            <% end %></td>
        <td><%= workout.distance %></td>
        <td><%= workout.duration %></td>
        <td class="actions text-nowrap">
            <%= render partial: 'shared/action_links', locals: { path: workout_path(workout), copy_path: new_workout_path(workout_id: workout), label: workout.location, allow_delete: workout.strava_id.blank? } %>
        </td>
    </tr>
    <% end %>
    </tbody>
</table>
<% paginate @workouts %>

app/views/workouts/edit.js.erb
$('#modal-dialog').html("<%= escape_javascript(render(partial: 'form')) %>").modal('show');

var workoutOnCalendar = $('#workout-on').flatpickr({ allowInput: true });
$('#modal-dialog').on('blur', '#workout-on', function() {
  window.setTimeout(function() { workoutOnCalendar.close(); }, 250);
});

app/views/workouts/index.html.erb
<% if @workout_summary %>
    <div class="row">
        <div class="col workout-dashboard">
            <div class="item">last 30 days:</div>
            <div class="item"><div class="data"><%= @workout_summary[:workout_days] %></div>workout days</div>
            <div class="item"><div class="data"><%= @workout_summary[:mileage] %></div>km</div>
            <div class="item"><div class="data"><%= @workout_summary[:duration] %></div>hours</div>
            <div class="item"><div class="data"><%= @workout_summary[:weight_range] %></div>weight</div>
            <div class="clear"></div>
        </div> <!-- end .workout-dashboard -->
    </div>
<% end %>

<div class="row">
    <div class="col-3 first-col reports-panel">
        <%= render 'duration_by_tag' %>
    </div>
    <div class="col-9 last-col list-panel">

        <%= render partial: 'shared/data_list_header', locals: { title: 'workouts', new_record_path: new_workout_path } %>

        <div class="data-list">
            <%= render partial: 'workouts' if @workouts.present? %>
        </div>
        <div class="tag-list">
            <%= tag_list 'workout' %>
        </div>
    </div> <!-- end .list-panel -->
</div> <!-- end .row -->

app/views/workouts/new.js.erb
$('#modal-dialog').html("<%= escape_javascript(render(partial: 'form')) %>").modal('show');

var workoutOnCalendar = $('#workout-on').flatpickr({ allowInput: true, defaultDate: new Date() });
$('#modal-dialog').on('blur', '#workout-on', function() {
  window.setTimeout(function() { workoutOnCalendar.close(); }, 250);
});

app/views/workouts/show.js.erb
$('#modal-dialog').html("<%= escape_javascript(render(partial: 'show')) %>").modal('show');