config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  get 'signup', to: 'people#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  post 'sms', to: 'sms#create', as: 'sms'

  resources :users
  resources :sessions

  resources :milestones
  resources :workouts
  resources :reminders do
    collection do
      put 'finish'
    end
  end
  resources :journals
  resources :contacts
  resources :connections
  resources :payments
  resources :accounts
  resources :people
  resources :links do
    collection do
      get 'find'
      get 'clean'
      get 'refresh_tags'
    end
  end
end

app/models/reminder.rb
class Reminder
  include Mongoid::Document
  include Mongoid::Timestamps::Short

  field :dsc, as: :description
  field :tg, as: :tags
  field :dn, as: :done, type: Boolean, default: false
  field :r_un, as: :repeat_until, type: Date
  field :d_at, as: :due_at, type: DateTime

  belongs_to :person
  belongs_to :reminder_type, class_name: 'Lookup', optional: true
  belongs_to :priority, class_name: 'Lookup', optional: true
  belongs_to :frequency, class_name: 'Lookup', optional: true

  validates :description, presence: true
  validates :due_at, presence: true
  paginates_per 8

  scope :outstanding, -> { where(done: false) }

  def done?
    !(done.zero? || done == 'f')
  end

  def self.todays(user)
    user.reminders.where(
      done: false, :due_at.gte => Time.zone.now.beginning_of_day, :due_at.lte => Time.zone.now.end_of_day
    )
  end

  def self.recent(user, days)
    user.reminders.gt(due_at: Time.zone.today - (days + 1))
  end

  def self.describe_due(user, at = Time.zone.now)
    summary = "due today:\n"
    user.reminders.where(done: false, :due_at.gte => at.beginning_of_day, :due_at.lte => at.end_of_day).each do |r|
      summary << "- #{r.priority.description} " if r.priority
      summary << "- #{r.description}\n"
    end
    summary
  end

  def self.summary(user, days)
    reminders = Reminder.recent(user, days)
    created = reminders.length
    completed = 0
    on_time = 0
    reminders.each do |r|
      completed += 1 if r.done
      on_time += 1 if r.done && r.due_at > r.updated_at.to_date
    end
    _completion_rate = (completed.to_f / created.to_f) * 100 # might use this later
    {
      created: created,
      on_time: on_time,
      completed: completed,
      completion_rate: created > 0 ? (completed.to_f / created.to_f) * 100 : 0
    }
  end

  def to_s
    "#{due_at} - #{description}"
  end
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  include ApplicationHelper

  before_action :set_reminder, only: %i[show edit update destroy]

  # GET /reminders
  def index
    authorize Reminder
    @reminders = current_user.reminders.outstanding.asc(:due_at)
    if params[:tag]
      @reminders = @reminders.where(tags: /#{params[:tag]}/)
      @tag = params[:tag]
    end
    @reminders = @reminders.where(description: /#{params[:q]}/i) if params[:q]
    @reminders = @reminders.page(params[:page])
    @reminder_summary = Reminder.summary(current_user, 31)
  end

  # GET /reminders/1.js
  def show
    authorize @reminder
  end

  # GET /reminders/new.js
  def new
    @types = Lookup.where(category: 16).order_by(description: :asc)
    @priorities = Lookup.where(category: 11).order_by(code: :asc)
    @frequencies = Lookup.where(category: 36).order_by(code: :asc)
    @reminder = params[:reminder_id] ? Reminder.find(params[:reminder_id]).dup : Reminder.new
  end

  # GET /reminders/1/edit.js
  def edit
    @reminder = Reminder.find(params[:id])
    authorize @reminder
    @types = Lookup.where(category: 16).order_by(description: :asc)
    @priorities = Lookup.where(category: 11).order_by(code: :asc)
    @frequencies = Lookup.where(category: 36).order_by(code: :asc)
  end

  # POST /reminders
  def create
    @reminder = current_user.reminders.build(reminder_params)
    if @reminder.save
      current_user.tag('reminder', @reminder.tags)
      flash[:notice] = "reminder #{condense(@reminder.description)} was created."
      redirect_to reminders_path
    end
  end

  # PUT /reminders/1
  def update
    @reminder = Reminder.find(params[:id])
    authorize @reminder
    if @reminder.update_attributes(reminder_params)
      current_user.tag('reminder', @reminder.tags)
      flash[:notice] = "reminder #{condense(@reminder.description)} was updated."
      redirect_to reminders_path
    end
  end

  # DELETE /reminders/1
  def destroy
    @reminder = Reminder.find(params[:id])
    authorize @reminder
    @reminder.destroy
    redirect_to reminders_url
  end

  # POST /reminders/finish
  def finish
    params[:reminder].each do |reminder_id, attr|
      reminder = Reminder.find(reminder_id)
      reminder.update_attribute(:done, attr[:done])
    end
    redirect_to reminders_path
  end

  private

  def set_reminder
    @reminder = Reminder.find(params[:id])
  end

  def reminder_params
    params.require(:reminder).permit(
      :description, :tags, :done, :repeat_until, :due_at, :reminder_type_id, :priority_id, :frequency
    )
  end
end

app/helpers/reminders_helper.rb
module RemindersHelper
  def due_with_class(reminder)
    due_class = if reminder.due_at.to_time < Time.zone.now
                  'overdue'
                elsif reminder.due_at == Time.zone.now
                  'due'
                else
                  ''
                end
    content_tag(:div, reminder.due_at.strftime('%a %b %d, %y'), class: due_class)
  end
end

app/views/reminders/_form.html.erb
<%= form_with(model: @reminder, local: true) do |f| %>
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><%= @reminder.new_record? ? 'new' : 'update' %> reminder</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container">
                    <div class="form-group row">
                        <%= f.label(:description, class: 'col-sm-2 col-form-label text-right') %>
                        <div class="col-sm-10">
                            <%= f.text_area(:description, rows: 3, class: 'form-control focus') %>
                        </div>
                    </div>
                    <div class="form-group row">
                        <%= f.label(:reminder_type_id, 'Type', class: 'col-sm-2 col-form-label text-right') %>
                        <div class="col-sm-4">
                            <%= f.collection_select(:reminder_type_id, @types, :id, :description, { prompt: true }, class: 'form-control') %>
                        </div>
                        <%= f.label(:priority_id, class: 'col-sm-2 col-form-label text-right') %>
                        <div class="col-sm-4">
                            <%= f.collection_select(:priority_id, @types, :id, :description, { prompt: true }, class: 'form-control') %>
                        </div>
                    </div>
                    <div class="form-group row">
                        <%= f.label(:due_at, class: 'col-sm-2 col-form-label text-right') %>
                        <div class="col-sm-4">
                            <%= f.text_field(:due_at, id: 'due-at', class: 'form-control') %>
                        </div>
                        <%= f.label(:done, class: 'col-sm-2 col-form-label text-right') %>
                        <div class="col-sm-4">
                            <%= f.check_box :done, id: 'reminder_done', class: 'form-control' %>
                        </div>
                    </div>
                    <div class="form-group row">
                        <%= f.label(:tags, class: 'col-sm-2 col-form-label text-right') %>
                        <div class="col-sm-6 pr-0">
                            <%= f.text_field(:tags, id: 'reminder-tags', class: 'form-control') %>
                        </div>
                        <div class="col-sm-4 pl-0">
                            <%= render partial: 'shared/tags_field', locals: { kind: 'reminder', desc_field: nil } %>
                        </div>
                    </div>
                </div>
            </div> <!-- end .modal-body -->
            <div class="modal-footer">
                <div class="form-group row text-right">
                    <div class="col">
                        <%= link_to('cancel', '#', data: { dismiss: 'modal' }) %>
                        <%= f.submit class: 'btn btn-primary' %>
                    </div>
                </div>
            </div> <!-- end .modal-footer -->
        </div> <!-- end .modal-content -->
    </div> <!-- end .modal-dialog -->
<% end %>

app/views/reminders/_reminders.html.erb
<%= filters_links %>
<%= form_tag(finish_reminders_path, method: 'put') do %>
    <table class="table table-sm table-hover">
    <thead>
        <tr><th>date</th><th>type</th><th>priority</th><th>description</th><th>actions</th><th>done</th></tr>
    </thead>
    <tbody>
        <% @reminders.each do |reminder| %>
        <tr>
            <td><%= due_with_class(reminder) %></td>
            <td><%= reminder.reminder_type.description if reminder.reminder_type %></td>
            <td><%= reminder.priority.description if reminder.priority %></td>
            <td><%= link_to(condense(reminder.description, 40), edit_reminder_path(reminder), remote: true) %></td>
            <td class="actions text-nowrap">
                <%= render partial: 'shared/action_links', locals: { path: reminder_path(reminder), copy_path: new_reminder_path(reminder_id: reminder), label: condense(reminder.description), allow_delete: true } %>
            </td>
            <td width="5%"><%= check_box_tag("reminder[#{reminder.id.to_s}][done]", 1, reminder.done == 1) %></td>
        </tr>
        <% end %>
    </tbody>
    </table>
    <div class="text-right">
        <%= button_tag(nil, class: 'btn btn-info') do %>
            <span class="icon-check"></span> finish
        <% end %>
    </div>
<% end %>
<%= paginate @reminders %>

app/views/reminders/_show.html.erb
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">reminder details</h5>
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-md-5 display-label">type</div>
                <div class="col-md-7"><%= @reminder.reminder_type.description if @reminder.reminder_type %></div>
            </div>
            <div class="row">
                <div class="col-md-5 display-label">priority</div>
                <div class="col-md-7"><%= @reminder.priority.description if @reminder.priority %></div>
            </div>
            <div class="row">
                <div class="col-md-5 display-label">due</div>
                <div class="col-md-7"><%= @reminder.due_at.strftime("%a %b %d, %y") %></div>
            </div>
            <div class="row">
                <div class="col-md-5 display-label">tags</div>
                <div class="col-md-7"><%= @reminder.tags %></div>
            </div>
            <div class="row">
                <div class="col-md-5 display-label">description</div>
                <div class="col-md-7"><%= @reminder.description %></div>
            </div>
            <div class="row">
                <div class="col-md-5 display-label">created on</div>
                <div class="col-md-7"><%= @reminder.created_at.strftime("%a %b %d, %y") %></div>
            </div>
        </div> <!-- /.modal-body -->
    </div> <!-- /.modal-content -->
</div> <!-- /.modal-dialog -->

app/views/reminders/edit.js.erb
$('#modal-dialog').html("<%= escape_javascript(render(partial: 'form')) %>").modal('show');

var dueAtCalendar = $('#due-at').flatpickr({ allowInput: true, enableTime: true });

app/views/reminders/index.html.erb
<% if @reminder_summary %>
    <div class="row">
        <div class="col-12 reminder-dashboard">
            <div class="item">last 30 days:</div>
            <div class="item"><div class="data"><%= @reminder_summary[:created] %></div>created</div>
            <div class="item"><div class="data"><%= @reminder_summary[:completed] %></div>completed</div>
            <div class="item"><div class="data"><%= number_to_percentage(@reminder_summary[:completion_rate], precision: 0) %></div>rate</div>
            <div class="item"><div class="data"><%= @reminder_summary[:on_time] %></div>on time</div>
            <div class="clear"></div>
        </div> <!-- end .reminder-dashboard -->
    </div>
<% end %>

<div class="row">
    <div class="col-12">
        <%= render partial: 'shared/data_list_header', locals: { title: 'reminders', new_record_path: new_reminder_path } %>

        <div class="data-list">
            <%= render partial: 'reminders' if @reminders.present? %>
        </div>

        <div class="tag-list">
            <%= tag_list 'reminder' %>
        </div>
    </div>
</div>

app/views/reminders/new.js.erb
$('#modal-dialog').html("<%= escape_javascript(render(partial: 'form')) %>").modal('show');

var dueAtCalendar = $('#due-at').flatpickr({ allowInput: true, enableTime: true, defaultDate: new Date() });

app/views/reminders/show.js.erb
$('#modal-dialog').html("<%= escape_javascript(render(partial: 'show')) %>").modal('show');