config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  get 'signup', to: 'people#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  post 'sms', to: 'sms#create', as: 'sms'

  resources :users
  resources :sessions

  resources :milestones
  resources :workouts
  resources :reminders do
    collection do
      put 'finish'
    end
  end
  resources :journals
  resources :contacts
  resources :connections
  resources :payments
  resources :accounts
  resources :people
  resources :links do
    collection do
      get 'find'
      get 'clean'
      get 'refresh_tags'
    end
  end
end

app/models/payment.rb
class Payment
  include Mongoid::Document
  include Mongoid::Timestamps::Short

  field :dsc, as: :description
  field :tg, as: :tags
  field :am, as: :amount, type: Float
  field :p_on, as: :payment_on, type: Date
  field :un, as: :until, type: Date

  belongs_to :person
  belongs_to :from_account, class_name: 'Account', optional: true
  belongs_to :to_account, class_name: 'Account', optional: true
  belongs_to :frequency, class_name: 'Lookup', optional: true

  validates :amount, presence: true
  validates :payment_on, presence: true
  paginates_per 15

  attr_accessor :payment_type

  def account_name
    return "#{from_account.name} -> #{to_account.name}" if from_account && to_account
    return from_account.name if from_account
    return to_account.name if to_account
  end

  def type
    return 'transfer' if from_account && to_account
    return 'deposit' if to_account
    return 'expense' if from_account
  end

  def transfer?
    type == 'transfer'
  end

  def deposit?
    type == 'deposit'
  end

  def expense?
    type == 'expense'
  end

  def apply(reverse = false)
    amt = amount
    amt *= -1 if reverse
    if from_account
      from_account.units -= (amt / from_account.price)
      from_account.save
    end
    return unless to_account
    to_account.units += (amt / to_account.price)
    to_account.save
  end

  def reverse
    apply true
  end

  def update_amount_and_adjust_account(new_amount)
    reverse
    self.amount = new_amount
    save
    apply
  end

  def build_repeat
    return unless frequency && next_due <= Time.zone.today
    # repeating and due
    new_payment = clone
    new_payment.payment_on = next_due
    new_payment.save
    new_payment.apply
    # recursion
    new_payment.build_repeat
    self.frequency = nil
    self.until = nil
    save
  end

  def next_due
    freq_code = frequency.code.to_i
    if freq_code < 15 # daily, weekly or biweekly
      due = payment_on + freq_code
    elsif freq_code == 15 # twice monthly
      last_day_of_month = Date.civil(payment_on.year, payment_on.month, -1).day
      if payment_on.day == last_day_of_month
        due = payment_on >> 1
        due = Date.civil(due.year, due.month, 15)
      else
        day = payment_on.day < 15 ? 15 : -1
        due = Date.civil(payment_on.year, payment_on.month, day)
      end
    elsif freq_code == 30 # monthly
      due = payment_on >> 1
    elsif freq_code == 365
      due = payment_on >> 12
    end
    due
  end

  def self.recent_expenses(user, days)
    user.payments.where(to_account: nil).ne(from_account: nil).gt(payment_on: Time.zone.today - days)
  end

  def self.recent_transfers(user, days)
    user.payments.ne(from_account: nil).ne(to_account: nil).gt(payment_on: Time.zone.today - days)
  end

  def self.recent_deposits(user, days)
    user.payments.where(from_account: nil).ne(to_account: nil).gt(payment_on: Time.zone.today - days)
  end

  def self.find_recent(user, days)
    all = recent_expenses(user, days)
    all += recent_transfers(user, days)
    all += recent_deposits(user, days)
    all.sort! { |x, y| y.payment_on <=> x.payment_on }
  end

  def self.upcoming(user)
    user.payments.ne(frequency: nil).each(&:build_repeat)
    user.payments.ne(frequency: nil).desc(:payment_on)
  end

  def self.days_with_expenses?(user, days)
    user.payments.ne(from_account: nil).between(payment_on: Time.zone.today - days..Time.zone.today + 1)
        .distinct(:payment_on).count
  end

  def self.expenses_by_tag(user, days)
    result_hash = {}
    recent_expenses(user, days).each do |exp|
      next if exp.tags.nil?
      exp.tags.split.each do |tag|
        result_hash[tag] ||= 0
        result_hash[tag] = result_hash[tag] + exp.amount.abs
      end
    end
    result_array = result_hash.sort { |a, b| b[1] <=> a[1] }
    result_array.first(8)
  end

  def self.summary(user, days = 31)
    deposits = Payment.recent_deposits(user, days)
    total = 0
    balance = 0
    income = 0

    deposits.each do |dep|
      income += dep.amount
    end
    expenses = Payment.recent_expenses(user, days)
    expenses.each do |exp|
      total += exp.amount.abs
    end
    user.active_accounts.each do |account|
      balance += account.balance
    end
    {
      total: total,
      net_change: income - total,
      per_day: total / days,
      buy_nothing_days: days - Payment.days_with_expenses?(user, days),
      balance: balance
    }
  end

  def to_s
    "#{amount} #{account_name} :: #{description}"
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: %i[show edit update destroy]

  # GET /payments
  def index
    authorize Payment
    @payments = current_user.payments.where(:payment_on.gt => 1.year.ago).desc(:payment_on)
    @accounts = current_user.accounts.active
    @payments = @payments.where(description: /#{params[:q]}/i) if params[:q]
    if params[:tag]
      @payments = @payments.where(tags: /#{params[:tag]}/)
      @tag = params[:tag]
    end
    @payments = @payments.page(params[:page])

    @upcoming_payments = Payment.upcoming(current_user)
    @money_summary = Payment.summary(current_user, 31)
    @expenses_by_tag = Payment.expenses_by_tag(current_user, 31)
  end

  # GET /payments/1.js
  def show
    authorize @payment
  end

  # GET /payments/new.js
  def new
    @payment = params[:payment_id] ? Payment.find(params[:payment_id]).dup : Payment.new
    authorize @payment
    stuff_for_form
    @payment = Payment.find(params[:payment_id]).dup if params[:payment_id]
  end

  # GET /payments/1/edit.js
  def edit
    authorize @payment
    stuff_for_form
  end

  # POST /payments
  def create
    @payment = current_user.payments.build(payment_params)
    authorize @payment
    if @payment.save
      @payment.apply
      current_user.tag('payment', @payment.tags)
      flash[:notice] = 'payment was created.'
      redirect_to payments_path
    end
  end

  # PUT /payments/1
  def update
    authorize @payment
    new_amount = params[:payment][:amount].to_f
    @payment.update_amount_and_adjust_account(new_amount)
    params[:payment].delete('amount')
    params[:payment][:from_account] = Account.find(params[:payment][:from_account]) if params[:payment][:from_account].present?
    params[:payment][:to_account] = Account.find(params[:payment][:to_account]) if params[:payment][:to_account].present?
    params[:payment][:frequency] = Lookup.find(params[:payment][:frequency]) if params[:payment][:frequency].present?

    if @payment.update_attributes(payment_params)
      current_user.tag('payment', @payment.tags)
      flash[:notice] = 'payment was updated.'
      redirect_to payments_path
    end
  end

  # DELETE /payments/1
  def destroy
    authorize @payment
    @payment.apply(true)
    @payment.destroy
    redirect_to payments_path
  end

  private

  def stuff_for_form
    @accounts = current_user.accounts.active.order_by(name: :asc)
    @frequencies = Lookup.where(category: 36).all
  end

  def set_payment
    @payment = Payment.find(params[:id])
  end

  def payment_params
    params.require(:payment).permit(:amount, :description, :tags, :payment_on, :until, :from_account, :to_account, :frequency)
  end
end

app/views/payments/_accounts.html.erb
<div id="payments-accounts" class="d-none card">
    <div class="card-header"><h5>accounts</h5></div>
    <div class="card-body">
        <div class="container-fluid">
            <% accounts.each do |account| %>
            <div class="row no-gutters">
                <div class="col-5">
                    <% if account.url && !account.url.empty? %>
                        <%= link_to account.name, account.url, target: '_blank' %>
                    <% else %>
                        <%= account.name %>
                    <% end %>
                </div>
                <div class="col-6">
                    <% if account.price_url && account.price_url.length > 0 %>
                        <%= link_to number_to_currency(account.balance), account.price_url, target: '_blank' %>
                    <% else %>
                        <%= number_to_currency account.balance %>
                    <% end %>
                </div>
                <div class="col-1">
                    <%= link_to(edit_account_path(account), remote: true, class: 'actions') do %>
                        <span class="icon-edit"></span>
                    <% end %>
                </div>
            </div>
            <% end %>
            <div class="row no-gutters">
                <div class="col text-right">
                    <%= link_to(new_account_path, remote: true, class: 'btn btn-small') do %>
                        <span class="icon-plus"></span>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/payments/_expenses_by_tag.html.erb
<div id="payments-top-tags" class="card">
    <div class="card-header"><h5>expenses by tag</h5></div>
    <div class="card-body">
        <% @expenses_by_tag.each do |e| %>
            <% percentage = ((e[1] / @money_summary[:total]) * 100).to_i.to_s %>
            <%= "#{e[0]} #{number_to_currency(e[1])} [#{percentage}%]" %><br/>
            <%= image_tag('redbar.gif', width: "#{percentage.to_i * 2}", class: 'bar') %><br/>
        <% end %>
    </div>
</div>

app/views/payments/_form.html.erb
<%= form_with(model: @payment, local: true) do |f| %>
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><%= @payment.new_record? ? 'new' : 'update' %> payment</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container">
                    <div class="form-group row">
                        <%= f.label(:payment_on, class: 'col-sm-2 col-form-label text-right') %>
                        <div class="col-sm-4">
                            <%= f.text_field(:payment_on, id: 'payment-on', class: 'form-control') %>
                        </div>
                        <%= f.label(:amount, class: 'col-sm-2 col-form-label text-right') %>
                        <div class="col-sm-4">
                            <%= f.text_field(:amount, class: 'form-control focus') %>
                        </div>
                    </div>
                    <div class="form-group row">
                        <%= f.label(:from_account, class: 'col-sm-2 col-form-label text-right') %>
                        <div class="col-sm-4">
                            <%= f.collection_select(:from_account, @accounts, :id, :name, { include_blank: true }, class: 'form-control') %>
                        </div>
                        <%= f.label(:to_account, class: 'col-sm-2 col-form-label text-right') %>
                        <div class="col-sm-4">
                            <%= f.collection_select(:to_account, @accounts, :id, :name, { include_blank: true }, class: 'form-control') %>
                        </div>
                    </div>
                    <div class="form-group row">
                        <%= f.label(:description, class: 'col-sm-2 col-form-label text-right') %>
                        <div class="col-sm-10">
                            <%= f.text_field(:description, id: 'payment-description', class: 'form-control') %>
                        </div>
                    </div>
                    <div class="form-group row">
                        <%= f.label(:tags, class: 'col-sm-2 col-form-label text-right') %>
                        <div class="col-sm-6 pr-0">
                            <%= f.text_field(:tags, id: 'payment-tags', class: 'form-control') %>
                        </div>
                        <div class="col-sm-4 pl-0">
                            <%= render partial: 'shared/tags_field', locals: { kind: 'payment', desc_field: 'payment-description' } %>
                        </div>
                    </div>
                    <fieldset>
                        <legend>schedule</legend>
                        <div class="form-group row">
                            <%= f.label(:frequency, class: 'col-sm-2 col-form-label text-right') %>
                            <div class="col-sm-10">
                                <%= f.collection_select(:frequency, @frequencies, :id, :description, { include_blank: true }, class: 'form-control') %>
                            </div>
                        </div>
                        <div class="form-group row">
                            <%= f.label(:until, class: 'col-sm-2 col-form-label text-right') %>
                            <div class="col-sm-10">
                                <%= f.text_field(:until, id: 'payment-until', class: 'form-control') %>
                            </div>
                        </div>
                    </fieldset>
                </div>
            </div> <!-- end .modal-body -->
            <div class="modal-footer">
                <div class="form-group row text-right">
                    <div class="col">
                        <%= link_to('cancel', '#', data: { dismiss: 'modal' }) %>
                        <%= f.submit class: 'btn btn-primary' %>
                    </div>
                </div>
            </div> <!-- end .modal-footer -->
        </div> <!-- end .modal-content -->
    </div> <!-- end .modal-dialog -->
<% end %>

app/views/payments/_payments.html.erb
<%= filters_links %>
<table class="table table-sm table-hover">
    <thead>
        <tr><th>description</th><th>amount</th><th>account</th><th>date</th><th>actions</th></tr>
    </thead>
    <tbody>
        <% @payments.each do |payment| %>
        <tr>
            <td><%= link_to(condense(payment.description), edit_payment_path(payment), remote: true) %></td>
            <td><div class="<%= "#{payment.type}-amount" %>"><%= number_to_currency payment.amount %></div></td>
            <td><%= payment.account_name %></td>
            <td><%= payment.payment_on.strftime("%a %b %d, %y") %></td>
            <td class="actions text-nowrap">
                <%= render partial: 'shared/action_links', locals: { path: payment_path(payment), copy_path: new_payment_path(payment_id: payment), label: condense(payment.description), allow_delete: true } %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>
<%= paginate @payments %>

app/views/payments/_show.html.erb
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">transaction details</h5>
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-md-5 display-label">date</div>
                <div class="col-md-7"><%= @payment.payment_on.strftime("%a %b %d, %y")  %></div>
            </div>
            <div class="row">
                <div class="col-md-5 display-label">account</div>
                <div class="col-md-7"><%= @payment.account_name %></div>
            </div>
            <div class="row">
                <div class="col-md-5 display-label">amount</div>
                <div class="col-md-7"><%= @payment.amount %></div>
            </div>
            <div class="row">
                <div class="col-md-5 display-label">description</div>
                <div class="col-md-7"><%= @payment.description %></div>
            </div>
        </div> <!-- /.modal-body -->
    </div> <!-- /.modal-content -->
</div> <!-- /.modal-dialog -->

app/views/payments/_upcoming.html.erb
<div id="future-payment-list" class="card mb-2">
    <div class="card-header"><h5>upcoming</h5></div>
    <div class="card-body">
        <table class="table table-sm table-hover mb-0">
            <tbody>
                <% @upcoming_payments.each do |payment| %>
                    <tr>
                        <td><%= condense(payment.description) %></td>
                        <td><div class="<%= "#{payment.type}-amount" %>"><%= number_to_currency payment.amount %></div></td>
                        <td><%= payment.account_name %></td>
                        <td>in <%= (payment.next_due - Date.today).to_i %> days</td></tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/payments/edit.js.erb
$('#modal-dialog').html("<%= escape_javascript(render(partial: 'form')) %>").modal('show');

var paymentOnCalendar = $('#payment-on').flatpickr({ allowInput: true });
$('#modal-dialog').on('blur', '#payment_payment_on', function() {
  window.setTimeout(function() { paymentOnCalendar.close(); }, 250);
});

var untilCalendar = $('#payment-until').flatpickr({ allowInput: true });
$('#modal-dialog').on('blur', '#payment_until', function() {
  window.setTimeout(function() { untilCalendar.close(); }, 250);
});

app/views/payments/index.html.erb
<% if @money_summary %>
    <div class="row">
        <div class="col-12 payment-dashboard">
            <div class="item">last 30 days:</div>
            <div class="item"><div class="data"><%= number_to_currency @money_summary[:net_change] %></div>net change</div>
            <div class="item"><div class="data"><%= number_to_currency @money_summary[:per_day] %></div>per day</div>
            <div class="item"><div class="data"><%= @money_summary[:buy_nothing_days] %></div>buy nothing days</div>
            <div class="item"><div class="data"><%= number_to_currency @money_summary[:balance] %></div>net worth</div>
            <div class="clear"></div>
        </div> <!-- end .payment-dashboard -->
    </div>
<% end %>

<div class="row">
    <div class="col-3 first-col reports-panel">
        <div class="btn-group mb-2">
            <button type="button" class="btn btn-primary btn-show-top-tags active">top tags</button>
            <button type="button" class="btn btn-primary btn-show-accounts">accounts</button>
        </div>

        <%= render partial: 'accounts', locals: { accounts: @accounts } %>
        <%= render 'expenses_by_tag' %>
    </div>
    <div class="col-9 last-col list-panel">
        <%= render partial: 'upcoming' if @upcoming_payments.present? %>
        <%= render partial: 'shared/data_list_header', locals: { title: 'transactions', new_record_path: new_payment_path } %>
        <div class="data-list">
            <% if @payments.present? %>
                <%= render partial: 'payments' %>
            <% elsif (@payments.empty? && params[:q].present?) %>
                you searched for <%= params[:q] %> but you didn't find anything
            <% end %>
        </div>

        <div class="tag-list">
            <%= tag_list 'payment' %>
        </div>
    </div> <!-- end .list-panel -->
</div> <!-- end .row -->

app/views/payments/new.js.erb
$('#modal-dialog').html("<%= escape_javascript(render(partial: 'form')) %>").modal('show');

var paymentOnCalendar = $('#payment-on').flatpickr({ allowInput: true, defaultDate: new Date() });
$('#modal-dialog').on('blur', '#payment_payment_on', function() {
  window.setTimeout(function() { paymentOnCalendar.close(); }, 250);
});

var untilCalendar = $('#payment-until').flatpickr({ allowInput: true });
$('#modal-dialog').on('blur', '#payment_until', function() {
  window.setTimeout(function() { untilCalendar.close(); }, 250);
});

app/views/payments/show.js.erb
$('#modal-dialog').html("<%= escape_javascript(render(partial: 'show')) %>").modal('show');