config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  get 'signup', to: 'people#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  post 'sms', to: 'sms#create', as: 'sms'

  resources :users
  resources :sessions

  resources :milestones
  resources :workouts
  resources :reminders do
    collection do
      put 'finish'
    end
  end
  resources :journals
  resources :contacts
  resources :connections
  resources :payments
  resources :accounts
  resources :people
  resources :links do
    collection do
      get 'find'
      get 'clean'
      get 'refresh_tags'
    end
  end
end

app/models/journal.rb
class Journal
  include Mongoid::Document
  include Mongoid::Timestamps::Short

  field :en, as: :entry
  field :tg, as: :tags
  field :e_on, as: :entry_on, type: Date

  belongs_to :person
  belongs_to :journal_type, class_name: 'Lookup', optional: true

  validates :entry, presence: true
  validates :entry_on, presence: true
  paginates_per 15

  def to_s
    entry[0, 30]
  end
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  before_action :set_journal, only: %i[show edit update destroy]

  # GET /journals
  def index
    authorize Journal
    @journals = current_user.journals.desc('entry_on')
    @journals = @journals.where(entry: /#{params[:q]}/i) if params[:q]
    if params[:tag]
      @journals = @journals.where(tags: /#{params[:tag]}/)
      @tag = params[:tag]
    end
    @journals = @journals.page(params[:page])
  end

  # GET /journals/1.js
  def show
    authorize @journal
  end

  # GET /journals/1/new.js
  def new
    @journal = params[:journal_id] ? Journal.find(params[:journal_id]).dup : Journal.new
    authorize @journal
    @types = Lookup.where(category: 7).order_by(description: :asc)
  end

  # GET /journals/1/edit.js
  def edit
    authorize @journal
    @types = Lookup.where(category: 7).order_by(description: :asc)
  end

  # POST /journals.js
  def create
    authorize Journal
    @journal = current_user.journals.build(journal_params)
    if @journal.save
      current_user.tag('journal', @journal.tags)
      @journals = current_user.journals.desc(:entry_on).page(params[:page])
      flash[:notice] = "journal entry was created."
    end
  end

  # PUT /journals/1.js
  def update
    authorize @journal
    # p = params[:journal].reject {|k, v| k == 'person' }
    # p[:journal_type] = Lookup.find(p[:journal_type])
    if @journal.update_attributes(journal_params)
      current_user.tag('journal', @journal.tags)
      @journals = current_user.journals.desc(:entry_on).page(params[:page])
      flash[:notice] = 'journal entry was updated.'
    end
  end

  # DELETE /journals/1
  def destroy
    authorize @journal
    @journal.destroy
    redirect_to(journals_path)
  end

  private

  def set_journal
    @journal = Journal.find(params[:id])
  end

  def journal_params
    params.require(:journal).permit(:entry, :tags, :entry_on, :journal_type_id)
  end
end

app/views/journals/_form.html.erb
<%= form_with(model: @journal) do |f| %>
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><%= @journal.new_record? ? 'new' : 'update' %> entry</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container">
                    <div class="form-group row">
                        <%= f.label(:entry, class: 'col-sm-2 col-form-label text-right') %>
                        <div class="col-sm-10">
                            <%= f.text_area(:entry, class: 'form-control focus') %>
                        </div>
                    </div>
                    <div class="form-group row">
                        <%= f.label(:entry_on, 'On', class: 'col-sm-2 col-form-label text-right') %>
                        <div class="col-sm-4">
                            <%= f.text_field(:entry_on, id: 'entry-on', class: 'form-control') %>
                        </div>
                        <%= f.label(:journal_type_id, 'Type', class: 'col-sm-2 col-form-label text-right') %>
                        <div class="col-sm-4">
                          <%= f.collection_select(:journal_type_id, @types, :id, :description, { }, class: 'form-control') %>
                        </div>
                    </div>
                    <div class="form-group row">
                        <%= f.label(:tags, class: 'col-sm-2 col-form-label text-right') %>
                        <div class="col-sm-6 pr-0">
                            <%= f.text_field(:tags, class: 'form-control', id: 'journal-tags') %>
                        </div>
                        <div class="col-sm-4 pl-0">
                            <%= render partial: 'shared/tags_field', locals: { kind: 'journal', desc_field: nil } %>
                        </div>
                    </div>
                </div>
            </div> <!-- end .modal-body -->
            <div class="modal-footer">
                <div class="form-group row text-right">
                    <div class="col">
                        <%= link_to('cancel', '#', data: { dismiss: 'modal' }) %>
                        <%= f.submit class: 'btn btn-primary' %>
                    </div>
                </div>
            </div> <!-- end .modal-footer -->
        </div> <!-- end .modal-content -->
    </div> <!-- end .modal-dialog -->
<% end %>

app/views/journals/_journals.html.erb
<%= filters_links %>
<table class="table table-sm table-hover">
    <thead>
        <tr><th>date</th><th>type</th><th>entry</th><th>actions</th></tr>
    </thead>
    <tbody>
    <% @journals.each do |journal| %>
        <tr>
            <td><%= link_to(journal.entry_on.strftime("%a %b %d, %y"), edit_journal_path(journal), remote: true, class: 'tip', data: { toggle: 'tooltip' }, title: "edit entry") %></td>
            <td><%= journal.journal_type.description if journal.journal_type %></td>
            <td><%= journal.entry[0,60] %></td>
            <td class="actions text-nowrap">
                <%= render partial: 'shared/action_links', locals: { path: journal_path(journal), copy_path: new_journal_path(journal_id: journal), label: 'entry', allow_delete: true } %>
            </td>
        </tr>
    <% end %>
    </tbody>
</table>
<%= paginate @journals %>

app/views/journals/_show.html.erb
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">entry details</h5>
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-md-5 display-label">date</div>
                <div class="col-md-7"><%= @journal.entry_on.strftime("%a %b %d, %y") %></div>
            </div>
            <div class="row">
                <div class="col-md-5 display-label">type</div>
                <div class="col-md-7"><%= @journal.journal_type.description if @journal.journal_type %></div>
            </div>
            <div class="row">
                <div class="col-md-5 display-label">enty</div>
                <div class="col-md-7"><%= @journal.entry %></div>
            </div>
        </div> <!-- /.modal-body -->
    </div></div> <!-- /.modal-content -->
</div> <!-- /.modal-dialog -->

app/views/journals/create.js.erb
<% if @journal.valid? %>
  $('#modal-dialog').modal('hide');
  $('#journal-list').html("<%= escape_javascript(render(partial: 'journals')) %>");
  addMessage('success', '<%= flash[:notice] %>');
  <% flash.discard(:notice) %>
<% else %>
  $('#modal-dialog').html("<%= escape_javascript(render(partial: 'form')) %>").modal('show');
<% end %>

app/views/journals/edit.js.erb
$('#modal-dialog').html("<%= escape_javascript(render(partial: 'form')) %>").modal('show');

var entryOnCalendar = $('#entry-on').flatpickr({ allowInput: true });
$('#modal-dialog').on('blur', '#entry-on', function() {
  window.setTimeout(function() { entryOnCalendar.close(); }, 250);
});

app/views/journals/index.html.erb
<%= render partial: 'shared/data_list_header', locals: { title: 'entries', new_record_path: new_journal_path } %>

<div id="journal-list" class="data-list">
  <%= render partial: 'journals' if @journals.present? %>
</div>

<div class="tag-list">
  <%= tag_list 'journal' %>
</div>

app/views/journals/new.js.erb
$('#modal-dialog').html("<%= escape_javascript(render(partial: 'form')) %>").modal('show');

var entryOnCalendar = $('#entry-on').flatpickr({ allowInput: true, defaultDate: new Date() });
$('#modal-dialog').on('blur', '#entry-on', function() {
  window.setTimeout(function() { entryOnCalendar.close(); }, 250);
});

app/views/journals/show.js.erb
$('#modal-dialog').html("<%= escape_javascript(render(partial: 'show')) %>").modal('show');

app/views/journals/update.js.erb
<% if @journal.valid? %>
	$('#modal-dialog').modal('hide');
	$('#journal-list').html("<%= escape_javascript(render(partial: 'journals')) %>");
  addMessage('success', '<%= flash[:notice] %>');
  <% flash.discard(:notice) %>
<% else %>
	$('#modal-dialog').html("<%= escape_javascript(render(partial: 'form')) %>").modal('show');
<% end %>